package bg.bas.iinf.sinus.hibernate.entity;

// Generated 2011-10-3 14:25:29 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SearchResults generated by hbm2java
 */
@Entity
@Table(name = "search_results")
public class SearchResults implements java.io.Serializable {

    private static final long serialVersionUID = 954144751403375661L;

    private Integer searchResultsId;
	private SavedSearches savedSearches;
	private String result;

	public SearchResults() {
	}

	public SearchResults(SavedSearches savedSearches, String result) {
		this.savedSearches = savedSearches;
		this.result = result;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "search_results_id", unique = true, nullable = false)
	public Integer getSearchResultsId() {
		return this.searchResultsId;
	}

	public void setSearchResultsId(Integer searchResultsId) {
		this.searchResultsId = searchResultsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "saved_searches_id", nullable = false)
	public SavedSearches getSavedSearches() {
		return this.savedSearches;
	}

	public void setSavedSearches(SavedSearches savedSearches) {
		this.savedSearches = savedSearches;
	}

	@Column(name = "result", nullable = false, length = 1000)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
